version: 2
jobs:
  trigger:
    working_directory: ~/workdir
    docker:
      - image: ubuntu:16.04

    steps:
      - run: apt-get update

      - run:
          name: Install AWS CLI
          command: "apt-get -y -qq install awscli"

      - run:
          name: Install Git
          command: "apt-get install git-core -y --no-install-recommends"

      - run:
          name: Trigger Build Process
          command: |
            aws s3 cp s3://vicoderspackagescredentials/trigger_build_process.config ~/workdir/trigger_build_process
            chmod +x ~/workdir/trigger_build_process
            ls -al ~/workdir
            ./trigger_build_process

workflows:
  version: 2
  packages:
    jobs:
      - trigger:
          filters:
            tags:
              only: /.*/
